### ISSUE TITLE
Unused dependencies?

### ISSUE THREAD

**Issue by jgierer12** [Sayegh7/emotion-reset#2]
Hi, it seems to me like this package has many unused dependencies:

https://github.com/Sayegh7/emotion-reset/blob/81ec82087d976680b6a9b0fad000d4e8aec153ec/package.json#L30-L31

https://github.com/Sayegh7/emotion-reset/blob/81ec82087d976680b6a9b0fad000d4e8aec153ec/package.json#L36-L37

https://github.com/Sayegh7/emotion-reset/blob/81ec82087d976680b6a9b0fad000d4e8aec153ec/package.json#L45

Can some of these be removed?

**Comment by Sayegh7** [comment]
Hello. Thanks for the comment, I'll get right on it

**Comment by Sayegh7** [comment]
@jgierer12 Fixed in release 1.0.4
