### ISSUE TITLE
@babel/polyfill is deprecated

### ISSUE THREAD

**Issue by mikecousins** [Sayegh7/emotion-reset#33]
**Describe the bug**
You now get this warning while installing emotion-reset.

warning emotion-reset > @babel/polyfill > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.

**To Reproduce**
1. Make a project with emotion-reset.
2. Install the packages using yarn or npm.
3. See error

**Expected behavior**
No warnings should be thrown

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
The official site says not to use it anymore: https://babeljs.io/docs/en/babel-polyfill

**Comment by Sayegh7** [comment]
Hi. Thanks for taking the time to report this bug. It should be fixed now 👍

**Comment by mikecousins** [comment]
Great, thanks!
