### ISSUE TITLE
Update to emotion 11

### ISSUE THREAD

**Issue by ubaldb** [Sayegh7/emotion-reset#44]
Hi @Sayegh7 ,
Is an update to [emotion 11](https://emotion.sh/docs/emotion-11) planned?
In emotion 11 the name of @emotion/core changed to @emotion/react. (see also [changelog](https://github.com/emotion-js/emotion/blob/master/packages/react/CHANGELOG.md#1100))
Thanks.

**Comment by Sayegh7** [comment]
Fixed in 3.0.0
